### ISSUE TITLE
segfault in __canonicalize_funcptr_for_compare during tests on HPPA architecture

### ISSUE THREAD

**Issue by rhertzog** [cpputest/cpputest#1145]
I'm forwarding the bug report that I received in Debian: https://bugs.debian.org/892063

The package build for the hppa architecture fails in the test suite:
```
./CppUTestTests
............................!........!..!..!..!..!
..!..!..!..!..!.................!....!.!......!...
..!..!..!make[2]: *** [Makefile:3402: tdd] Segmentation fault
```

The reporter provided the following investigation made with gdb:
```
Breakpoint 1, 0x000d7c24 in __canonicalize_funcptr_for_compare ()
(gdb) p/x $r26
$1 = 0xdeadbeef
(gdb) bt
#0  0x000d7c24 in __canonicalize_funcptr_for_compare ()
#1  0x000d637c in UtestShell::assertFunctionPointersEqual (
    this=0x17b2fc <TEST_UnitTestMacros_FUNCTIONPOINTERS_EQUAL_TEXTBehavesAsProperMacro_TestShell_instance>, expected=<error reading variable>,
    actual=<error reading variable>, text=0xee948 "Failed because it failed",
    fileName=<optimized out>, lineNumber=<optimized out>, testTerminator=...)
    at src/CppUTest/Utest.cpp:475
#2  0x00095f64 in TEST_UnitTestMacros_FUNCTIONPOINTERS_EQUAL_TEXTBehavesAsProperMacro_Test::testBody (this=<optimized out>) at tests/TestUTestMacro.cpp:734
#3  0x000d3ebc in helperDoTestBody (data=<optimized out>)
    at src/CppUTest/Utest.cpp:92
#4  0x000d75b8 in PlatformSpecificSetJmpImplementation (
    function=@0x16e6d2: 0xd3e98 <helperDoTestBody(void*)>, data=0x1891d0)
    at src/Platforms/Gcc/UtestPlatform.cpp:144
#5  0x000d4474 in Utest::run (this=0xdeadbeef) at src/CppUTest/Utest.cpp:575

(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x000d7c50 in __canonicalize_funcptr_for_compare ()
(gdb) disass $pc-16,$pc+16
Dump of assembler code from 0xd7c40 to 0xd7c60:
   0x000d7c40 <__canonicalize_funcptr_for_compare+40>:  copy r26,r3
   0x000d7c44 <__canonicalize_funcptr_for_compare+44>:  addil L%9000,dp,r1
   0x000d7c48 <__canonicalize_funcptr_for_compare+48>:  ldw 488(r1),r21
   0x000d7c4c <__canonicalize_funcptr_for_compare+52>:  depwi 0,31,2,r3
=> 0x000d7c50 <__canonicalize_funcptr_for_compare+56>:  ldw 0(r3),ret0
   0x000d7c54 <__canonicalize_funcptr_for_compare+60>:  ldo 10(ret0),r20
   0x000d7c58 <__canonicalize_funcptr_for_compare+64>:  cmpb,= r21,r20,0xd7c70 <__canonicalize_funcptr_for_compare+88>
   0x000d7c5c <__canonicalize_funcptr_for_compare+68>:  ldil L%-3ff2000,r31
End of assembler dump.
```

And he concluded with:
> It looks like `__canonicalize_funcptr_for_compare` needs to be improved to prevent access fault on garbage pointer, but maybe there's something that can be done in cpputest.

**Comment by basvodde** [comment]
Interesting. There is probably more than one of these? Is there any way that I can compile for this platform and run the tests? Or should I fix one, wait, etc ?

**Comment by rhertzog** [comment]
Hi, we have one porter machine listed in our database:
https://db.debian.org/machines.cgi?host=panama

You could contact the machine owner to ask for a temporary account to try to fix stuff.

Or maybe try to work with John David Anglin <dave.anglin@bell.net> who submitted the bug to me.

**Comment by basvodde** [comment]
Dropped Dave a mail.

**Comment by basvodde** [comment]
Tried to fix it. But it worked without fixing. They had fixed the issue in HPPA architecture. Closing this.
